### ISSUE TITLE
报错，不知道怎么回事

### ISSUE THREAD

**Issue by soul-cat** [LoseNine/Crack-Website-code#1]
self.dll = ctypes.CDLL("./dat/OCR.dll")
  File "C:\Users\asda\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by soul-cat** [comment]
自己傻逼了，问题关闭

**Comment by soul-cat** [comment]
1

**Comment by BeanKaKa** [comment]
请问如何解决的，我也遇到了
